# Generated by Django 2.2 on 2022-02-19 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20220218_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='avilable',
            new_name='available',
        ),
    ]
