# Generated by Django 2.2 on 2022-02-17 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='categ',
        ),
    ]
